# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 53e18541c81dfb2cc6b8183b0192f28de13cc0b68633eaf9093ef924499cd6561a53eccccf83b3921e492989b22b4f4c49ddf842b2c0d09c791133ef6ce36a5a

test:
  secret_key_base: 40eb0b486f2fc760e603347596dc3451b7ce09310abb3b0f93cf92de7b268a77df9e742b39805afd43dfd33ec28a3ab51ef2952f9b9298628aa86c609b27f90b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
